# Generated by Django 4.2.3 on 2023-07-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room',
            field=models.IntegerField(default=0),
        ),
    ]
